/**
 * Generates bundle/www/tools/icons/ — the nine icons aCelery uses, and nothing
 * else.
 *
 * The vendored Font Awesome 6 was 376 KB: a 74 KB stylesheet naming ~2,000
 * icons and three webfonts, of which the brands (119 KB) and regular (25 KB)
 * families were referenced by nothing at all. The product draws nine glyphs,
 * all solid.
 *
 * So this finds which icons the source actually names, reads their codepoints
 * out of Font Awesome's own stylesheet, subsets the solid woff2 to exactly
 * those glyphs, and writes a stylesheet with only the rules involved.
 *
 * The `<i class="fa-solid fa-gear">` idiom is unchanged, so nothing that uses
 * an icon has to know this happened. An icon that is *not* in the list renders
 * as nothing, which is why the list is derived from the source rather than
 * hand-written: adding an icon to a page and forgetting to add it here would
 * otherwise be a blank square.
 *
 * Run: node tool/build_icons.mjs   (or via tool/build_js.sh)
 */

import { readFileSync, writeFileSync, mkdirSync, rmSync, readdirSync, statSync }
  from "node:fs";
import { dirname, join, extname } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { createRequire } from "node:module";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

/* The JS toolchain lives in web/, so its packages resolve from there rather
   than from this file's directory. Same reason tool/build_js.sh runs esbuild
   with web/ as the working directory. */
const { default: subsetFont } = await import(
  pathToFileURL(
    createRequire(join(root, "web/package.json")).resolve("subset-font"),
  ).href
);
/* Font Awesome comes from npm, at the version the bundle used to vendor, so
   the 367 KB lives in neither the repo nor the install — the same arrangement
   tool/build_themes.mjs uses for Bootswatch. */
const source = join(root, "web/node_modules/@fortawesome/fontawesome-free");
const outDir = join(root, "bundle/www/tools/icons");

/** Every place an icon name can appear. */
const SEARCH = [
  "bundle/www/system",
  "bundle/www/user",
  "web/src",
];

/** Walks a directory for text files an icon name could be written in. */
function* files(dir) {
  for (const entry of readdirSync(dir)) {
    const path = join(dir, entry);
    if (statSync(path).isDirectory()) {
      if (entry === "node_modules") continue;
      yield* files(path);
    } else if ([".js", ".html", ".css", ".json"].includes(extname(entry))) {
      yield path;
    }
  }
}

/** The icon names actually written anywhere in the product. */
function iconsInUse() {
  const found = new Set();
  for (const dir of SEARCH) {
    for (const file of files(join(root, dir))) {
      for (const match of readFileSync(file, "utf8").matchAll(/fa-([a-z0-9-]+)/g)) {
        const name = match[1];
        // fa-solid / fa-regular / fa-brands are families, not icons.
        if (["solid", "regular", "brands"].includes(name)) continue;
        found.add(name);
      }
    }
  }
  return [...found].sort();
}

/**
 * Maps every icon name to its private-use codepoint, per the shipped
 * stylesheet.
 *
 * Minified Font Awesome groups aliases into one rule —
 * `.fa-table-cells,.fa-th{--fa:"\\f00a"}` — so the whole table is parsed once
 * and every selector in a group recorded, rather than pattern-matching each
 * name in turn and missing the ones that share a rule.
 */
function codepointTable() {
  const css = readFileSync(join(source, "css/all.min.css"), "utf8");
  const table = new Map();
  for (const rule of css.matchAll(
    /([^{}]*?)\{\s*--fa\s*:\s*"\\([0-9a-f]+)"\s*\}/gi,
  )) {
    const glyph = String.fromCodePoint(parseInt(rule[2], 16));
    for (const selector of rule[1].split(",")) {
      const name = selector.trim().match(/^\.fa-([a-z0-9-]+)$/i);
      if (name) table.set(name[1], glyph);
    }
  }
  return table;
}

function codepoints(names) {
  const table = codepointTable();
  const out = new Map();
  const missing = [];
  for (const name of names) {
    if (table.has(name)) out.set(name, table.get(name));
    else missing.push(name);
  }
  if (missing.length) {
    throw new Error(
      `no codepoint in the shipped Font Awesome for: ${missing.join(", ")}`,
    );
  }
  return out;
}

const faVersion = JSON.parse(
  readFileSync(join(source, "package.json"), "utf8"),
).version;

const names = iconsInUse();
const glyphs = codepoints(names);

const woff2 = readFileSync(join(source, "webfonts/fa-solid-900.woff2"));
const subset = await subsetFont(woff2, [...glyphs.values()].join(""), {
  targetFormat: "woff2",
});

rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, "icons.woff2"), subset);

const css = `/*! aCelery icons — generated by tool/build_icons.mjs, do not edit.
 *
 * Font Awesome ${faVersion}, subset to the ${names.length} glyphs this product draws.
 * The brands and regular families are not carried: nothing references them.
 *
 * Adding an icon to a page means re-running the generator, which finds it by
 * searching the source. An icon that is not in the subset renders as nothing.
 */
@font-face {
  font-family: "aCelery Icons";
  font-style: normal;
  font-weight: 900;
  font-display: block;
  src: url("icons.woff2") format("woff2");
}

.fa-solid,
.fas {
  font-family: "aCelery Icons";
  font-weight: 900;
  -moz-osx-font-smoothing: grayscale;
  -webkit-font-smoothing: antialiased;
  display: var(--fa-display, inline-block);
  font-style: normal;
  font-variant: normal;
  line-height: 1;
  text-rendering: auto;
}

.fa-solid::before,
.fas::before {
  content: var(--fa);
}

${[...glyphs]
  .map(([name, glyph]) =>
    `.fa-${name} { --fa: "\\${glyph.codePointAt(0).toString(16)}"; }`)
  .join("\n")}
`;
writeFileSync(join(outDir, "icons.css"), css);

const before =
  readdirSync(join(source, "webfonts"))
    .filter((f) => f.endsWith(".woff2"))
    .reduce((sum, f) => sum + statSync(join(source, "webfonts", f)).size, 0) +
  statSync(join(source, "css/all.min.css")).size;
const after = subset.length + Buffer.byteLength(css);

console.log(
  `bundle/www/tools/icons/: ${names.length} icons, ` +
    `${(after / 1024).toFixed(1)} KB (was ${(before / 1024).toFixed(0)} KB)`,
);
console.log(`  ${names.join(", ")}`);
